// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// Message actions
export const MESSAGE_CREATED_SUCCESS = 'MESSAGE_CREATED_SUCCESS';
export const MESSAGES_LOADED_SUCCESS = 'MESSAGES_LOADED_SUCCESS';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOADING_MESSAGES = 'LOADING_MESSAGES';

// Chatroom actions
export const LOADING_CHATROOMS = 'LOADING_CHATROOMS';
export const LOAD_CHATROOMS = 'LOAD_CHATROOMS';
export const SET_ACTIVE_ROOM = 'SET_ACTIVE_ROOM';
